# Site Settings
title: "Nature Hungry"
tagline: "Fully Open Source, Free Forever."
description: "One-stop resource for nature lovers in Singapore. We are a group of volunteers who are passionate about sharing information on Singapore's biodiversity."
url: "https://nature-hungry.github.io"
baseurl: ""

# Dependencies
markdown:         kramdown
highlighter:      rouge    # Pygments is largely deprecated; Rouge is the Jekyll 4 standard

# Custom vars
version:          2.1.0

# Backblaze Assets Directly
b2_url: "https://f003.backblazeb2.com/file/naturehungry/"

github:
  repo:           https://github.com/Nature-Hungry/nature-hungry.github.io
  username:       Nature-Hungry

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Nature Hungry
  url: https://github.com/nature-hungry/
  email: hello@wildsingapore.com

collections:
  entries:
    output: true
    permalink: /:collection/:path/

exclude:
- "*.py"