# Site Settings
<<<<<<< HEAD
title:            Nature Hungry
tagline:          'Fully Open Source, Free Forever.'
description:      'One-stop resource for nature lovers in Singapore. We are a group of volunteers who are passionate about sharing information on Singaporean biodiversity.'
url:              https://nature-hungry.github.io
baseurl:          ""
=======
title: "Nature Hungry"
tagline: "Fully Open Source, Free Forever."
description: "One-stop resource for nature lovers in Singapore. We are a group of volunteers who are passionate about sharing information on Singapore's biodiversity."
url: "https://nature-hungry.github.io"
baseurl: ""
>>>>>>> e90b9ec73d3227dc10a63e873ef088a8c10cf70d

# Dependencies
markdown:         kramdown
highlighter:      rouge    # Pygments is largely deprecated; Rouge is the Jekyll 4 standard

# Custom vars
version:          2.1.0

# Backblaze Assets Directly
b2_url: "https://f003.backblazeb2.com/file/naturehungry/"

github:
  repo:           https://github.com/Nature-Hungry/nature-hungry.github.io
  username:       Nature-Hungry

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-D6D1VPY6W2

collections:
  entries:
    output: true
    permalink: /:collection/:path/
  photoindexes:
    output: true
    permalink: /:collection/:path/

exclude:
- "*.py"