backend:
  name: github
  repo: Nature-Hungry/wildsingapore-jekyll
  branch: main
  base_url: https://api.netlify.com

media_folder: "assets/images/uploads" # Where media files will be saved
public_folder: "https://f003.backblazeb2.com/file/naturehungry/" # Where Jekyll will look for them

collections:
  - name: "species"
    label: "Species Factsheets"
    folder: "_entries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Body", name: "body", widget: "markdown"}